Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 0 from rod D to rod A
Move disk 0 from rod A to rod D
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
Move disk 1 from rod A to rod B
